name: devjeans-application-deploy-beanstalk

on:
  push:
    branched:
      - main # action 트리거 브랜치
  workflow_dispatch: # 수동 실행 옵션 (생략)

jobs:
  build:
    runs-on: ubuntu-latest # action 스크립트가 작동될 OS

    steps: # 작업 단계
      - name: Checkout source code # 단계별 이름, 구분자로 소스를 가져옴
        uses: actions/checkout@v2

      - name: Set up JDK 11 # JDK 설치
        uses: actions/setup-java@v1 # (5)
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        working-directory: .
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        working-directory: .
        run: ./gradlew clean build
        shell: bash

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDDTHHmm
          utcOffset: "+09:00"

      - name: Generate deployment package
        run: |
          mkdir -p deploy
          cp ./build/libs/*.jar deploy/
          cp Procfile deploy/Procfile
          cp -r .ebextensions deploy/.ebextensions
          cd deploy && zip -r Devjeans-label-${{steps.current-time.outputs.formattedTime}}-${{github.sha}} .

      - name: Deliver to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          aws s3 cp \
          --region ap-northeast-2 \
          deploy/Devjeans-label-${{steps.current-time.outputs.formattedTime}}-${{github.sha}}.zip s3://devjeans-cd/

      - name: Deploy Consumer to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Devjeans
          environment_name: Devjeans-env
          version_label: Devjeans-label-${{steps.current-time.outputs.formattedTime}}-${{github.sha}}
          region: ap-northeast-2
          deployment_package: deploy/Devjeans-label-${{steps.current-time.outputs.formattedTime}}-${{github.sha}}.zip